name: test
on:
  push:
    branches:
      - test

jobs:
  rsync-job:
    runs-on: ubuntu-latest
    steps:
      - name: Create tmp file
        run: |
          mkdir -p Rsync-My-File
          echo "Hello from https://github.com/GPTED/Rsync-My-File at $(date)" > Rsync-My-File/hello-from-gpted-rsync-my-File.txt
          echo "Another Hello from https://github.com/GPTED/Rsync-My-File at $(date)" > Rsync-My-File/another-hello-from-gpted-rsync-my-File.txt
      - name: Rsync My File
        uses: GPTED/Rsync-My-File@test
        with:
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY}}
          SOURCE: Rsync-My-File/
